keys:
  - &primary age1j5m502xft87rhgal0929h4urzspv3qd03mkrcek23rmm8dsuf5rq2465td
  - &pq age1pq1j2x20la3sryc22n2gzde4veqvjjgraa32ehz5t2xh2v463rex5nv7lzeengfhtryx24zfajt4qtg9rq63f3pkpkkvgawnq9jsdmjh3tfypmsvsmjnfw8t7cx42msujchgq8f4wrkmssqvjyussny0wsf4m4hej4l9v9huxsete34803uq32ce9rl0pywtdrcvg3zn2tx3r9m896z0zqkndtdrf9y4ujzrhjqqxdhg6eurakpjcdy6ayffrnayrdvu2xrqpsj3c2qk5kns8x28jxtsu72us5yvk2hzt35xmsl9y2jzjay07e3qqspw3wr24t953qqny4dq2yufrcp8a999cvpghut2vzeljwgh3nr2k5cyzhqffht5ug3ffe66uxpa73zgpkk9d45lpctlu5405acvuzcyr98wrj23wc2nsfta5zutgqh8she2ptjrf99x73aruzxdj4epwddvlxkupdmas92y4fu2lpkr0h7pz7e2kj5au7ruktj0phsf34zyfatcvzuzjnfwrpna7jq0ydm5ggjkkuxmpy0eg2x7kepx8n3yl0v2k6aevu50v55pgf6c3hm8g7pf927dny9n8aypcscpadetjuuw30px6ckc75qfwpup8dfjaqzaqefjut47kcs5dtpqh7yg97u9ypppd5nrl3cvuz532j2ggjjkjmnndf46jjfr4dy453pssjp6f87q259l5f2jttpjk7gxn3xc4qewgfljskgt3p8ylkd5kk2pj49re23a26ks5gp8e8u5rhgkk46wy4qaqmt6xf8tehlqq9ljad44qurgdz567thevvaglfwtt92fu3u0wqjdwje0jevzr4g7q548ds3uvjytnr6sc9jh9j26zcxwwdd0tc2vjjufg6ct85z2ds05ptd26rmw7zzenxgeyh7kzpmgyndjpumwxex33v5zzrmvulp92zpx7frghfzwz6ech2pwjekact78a6ru6pqdyzyzl0w62405typsu9zmsq5jtcl4nrs3f69u4ugmx9958pfyrdrp9x4q6ux72py449tscqgxyhu08xe6plxxssr3ksgqdx8np309dtzkwz43jy2kwatmlc8d3wscrkj3yytyhq6dwc9uf94xa69r99lhrqx0zpyd3u4k4nerlkhg3fsrfdnnks47d48wjx2qprh4jykwsdl57fgzuzfuny4fs7qdzxuzkqfkqcla9dul02qve7wwpzuj79l59j6gajpruy8cz3m4rnsjpn79gg0685zpsrxtnvvcm5qx50kp0r30tqcptyz0xp5smfwkjwhces8693mm36vnz7txdt403cq8nxp2qrxnr94zqj4c0xk2vyjzfdmljcq4d7ckqqjc5pfrjddk6nrzkyv6w788exgzryrg55ehavml0uny2z5klyk9yghv36r0vaakktc7jtrtsccqyuahxtqmvftze65zlmpjvv7jaz9jyrf3z9vmyj2za54nkwqtjy0y77dmz3uwr9rn7543fkqgvad79kka6ffq5fpg00zjf47fxfdywvn2vcevjpjax2vzk5qwv0yzxx69gas54jgrxf8wgnzfquhts65j2fgsjfuc8hszpuj80emmf33h3ssh0tjc5vk3t9pd3yccwm8tu782mu3n4y9na3ktjlghp6a46t0slsu7yuzr02ayq7uxsnd8de0zkcn03tktsrl3p0jpfselz5peedcs7j49jawzcf8a3ypptx8d62y0mhyhdjmcj9prx6ycy5tjxyyxr8xq2a9tjgffqzq9umlxkf2adyrx3lzqy5hxvf3kd4n643t9gkps3wjzn3mqkxg78awtgc3rs4h4qsskrxlwzag7r6rx4mr29r6cnptxw6q8wdutguuq83hudvhxhv2ca0xsufrqxsfjjx2c7ex52z7s258ra3z2qfzgc8f8t82

creation_rules:
  - path_regex: secrets/(wireguard|secrets|users|i3status|mail|syncthing|mullvad|nix\.conf|keepass|zipline)\.yaml$
    key_groups:
    - age:
      - *primary
      - *pq
  - path_regex: secrets/(knx|server)-syncthing-(cert|key).pem$
    key_groups:
    - age:
      - *primary
      - *pq
  - path_regex: secrets/acme.env.bin$
    key_groups:
    - age:
      - *primary
      - *pq
