keys:
  - &root-knx age1j5m502xft87rhgal0929h4urzspv3qd03mkrcek23rmm8dsuf5rq2465td
  - &server-knx age198xuk8yt5aqywee4zg7968ecq0ve8shhumq6fytxq5qyyp5mqvtssy66z0
  - &hm-knx age1tcsye90nmzdntlkzq58ml0t2tuye6t2unt9fyccy0yxn2ctmtfrq6dnq3t

creation_rules:
  - path_regex: secrets/(wireguard|users|syncthing|mullvad)\.yaml$
    key_groups:
    - age:
      - *server-knx
      - *root-knx
  - path_regex: secrets/keepass\.yaml$
    key_groups:
    - age:
      - *root-knx
  - path_regex: secrets/(syncthing-api|monitoring|mail-system)\.yaml$
    key_groups:
    - age:
      - *server-knx
  - path_regex: secrets/(i3status|zipline|mail|nix\.conf|last\.fm)\.yaml$
    key_groups:
    - age:
      - *hm-knx

  - path_regex: secrets/knx-syncthing-(cert|key).pem$
    key_groups:
    - age:
      - *root-knx
  - path_regex: secrets/server-syncthing-(cert|key).pem$
    key_groups:
    - age:
      - *server-knx

  - path_regex: secrets/acme.env.bin$
    key_groups:
    - age:
      - *root-knx
      - *server-knx
