{
  imports = [
    ./lsp
    ./cord.nix
    ./flash.nix
    ./treesj.nix
    ./nixvim.nix
    ./globals.nix
    ./conform.nix
    ./harpoon.nix
    ./gitsigns.nix
    ./neo-tree.nix
    ./telescope.nix
    ./colorizer.nix
    ./lightline.nix
    ./autopairs.nix
    ./mini-align.nix
    ./treesitter.nix
    ./mini-surround.nix
  ];
}
